#pipeline that deploys to the render cloud platform

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url:
        webhook_secret:

    - uses:
      with:
        render-token:
        github-token:
        service-id:
        retries:
        wait:
        sleep:
